### ISSUE TITLE
Will you make a Fragment Patcher to make an Patched ISO?

### ISSUE THREAD

**Issue by pftmclub** [Zero1UP/dot-Hack-Fragment-Patcher#4]
I really want to play Fragment online with physical Fat PS2 model, It's seem this Elf file required an Original Disc on Ps2 tray. Is there anyway to make it working with Open Ps2 Loader?

**Comment by Zero1UP** [comment]
> 
> 
> I really want to play Fragment online with physical Fat PS2 model, It's seem this Elf file required an Original Disc on Ps2 tray. Is there anyway to make it working with Open Ps2 Loader?

What does it currently do when you are using Open PS2 loader?

**Comment by dreamenddischarger** [comment]
I know this was closed, but I'm facing the same issue as OP I assume, when I try running the elf and booting the patch it just gives a black screen (most definitely because I don't have a disc in the system lol)

I'm not really sure how to make it redirect to OPL in this case...if this is anything, I know that for CodeBreaker you can replace CB_launch.elf with the OPL one so it opens that instead of attempting to launch the disc
